# This file is part of visvalingamwyatt.
# https://github.com/fitnr/visvalingamwyatt

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, fitnr <contact@fakeisthenewreal.org>

language: python

python:
    - 3.7
    - 3.8
    - 3.9

matrix:
    fast_finish: true
    allow_failures:
        - python: 2.7

install:
    - pip install docutils coverage
    - make install

script:
    - python setup.py test
    - vwsimplify --help
    - vwsimplify --threshold 0.001 tests/data/sample.json > /dev/null
    - vwsimplify --number 10 tests/data/sample.json > /dev/null
    - vwsimplify --ratio 0.90 tests/data/sample.json > /dev/null

after_script:
    - make cov
