# This file is part of visvalingamwyatt.
# https://github.com/fitnr/visvalingamwyatt
name: Test package

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Install package
        run: |
          python -m pip install -U pip
          pip install -e '.[tests]'

      - run: make cov
